### ISSUE TITLE
Implementar botões e o mecanismo de carrossel de imagens em si

### ISSUE THREAD

**Issue by Krepixie** [marcelosiqqueira/gabriel-agito#3]

**Comment by Stablest** [comment]
Adicionei a funcionalidade, precisa ser feito o css do componente. Precisa ser testada quando a api do google drive estiver funcionando.

**Comment by Stablest** [comment]
Quando foi feito o css, algo aconteceu que o botão não está mais funcionando, só estou deixando marcado que está bugado. Vou criar outra issue a partir disso.
